version: '3.1'

services:
  webserver:
    ports:
      - '8004:80'
###> doctrine/doctrine-bundle ###
#  database:
#    ports:
#      - '5432:5432'
###< doctrine/doctrine-bundle ###

###> symfony/mailer ###
  # mailer:
  #   image: schickling/mailcatcher
  #   ports: ["1025", "1080"]
###< symfony/mailer ###
